name: build

on : [push, pull_request]

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download SDK daml
        run: wget https://github.com/digital-asset/daml/releases/download/v2.3.2/daml-sdk-2.3.2-linux.
tar.gz
      - name: Install SDK
        run: cd sdk-2.3.2 && ./install.sh
      - name: Generate Java Code
        run: daml codegen java
      - name: Run and
        run: maven clean install