name: build

on : [push, pull_request]

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download and install
        run: |
                wget https://github.com/digital-asset/daml/releases/download/v2.3.2/daml-sdk-2.3.2-linux.tar.gz
                tar xzf daml-sdk-2.3.2-linux.tar.gz
                cd sdk-2.3.2
                ./install.sh
                echo "/home/runner/.daml/bin" >> $GITHUB_PATH
      - name: Generate Java code
        run: |
                daml build
                daml codegen java
      - name: Run tests and publish locally
        run: maven clean install