name: build

on : [push, pull_request]

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Download and install
        run: |
                wget https://github.com/digital-asset/daml/releases/download/v2.7.6/daml-sdk-2.7.6-linux.tar.gz
                tar xzf daml-sdk-2.7.6-linux.tar.gz
                cd sdk-2.7.6
                ./install.sh
                echo "/home/runner/.daml/bin" >> $GITHUB_PATH
      - name: Run unit tests
        run: sbt "cleanDarLib ; cleanSrcGenLib ; test"